const express = require('express');
const multer = require('multer');
const bodyParser = require("body-parser");
const path = require('path');
const mongoose = require("mongoose");
// const tools = require(__dirname + "/tools.js")
const schemas = require(__dirname + "/models/models.js")
var fs = require('fs');
const bcrypt = require('bcrypt')
const passport=require('passport');
const initializePassport=require('./passport-config');
const flash=require('express-flash');
const session=require('express-session');